### ISSUE TITLE
Can't install plugins with `go install`

### ISSUE THREAD

**Issue by WizMe-M** [meshapi/grpc-api-gateway#19]
# Context
I want to install plugins on my machine with `go install`.
So I call `go install github.com/meshapi/grpc-api-gateway@latest` command from [docs](https://meshapi.github.io/grpc-api-gateway/installation/#install-from-source).

# Expected result
Plugins' binaries are downloaded and extracted to `$gobin`.

# Actual result
Encountered error:
```
go: github.com/meshapi/grpc-api-gateway@latest: module github.com/meshapi/grpc-api-gateway@latest found (v0.0.11), but does not contain package github.com/meshapi/grpc-api-gateway
```

**Comment by peymanmortazavi** [comment]
@WizMe-M Ah yes, good catch, the documentation needs to get updated. I'll make a PR now.

Here's how you can install them:
```
go install github.com/meshapi/grpc-api-gateway/codegen/cmd/protoc-gen-openapiv3@latest
go install github.com/meshapi/grpc-api-gateway/codegen/cmd/protoc-gen-grpc-api-gateway@latest
```
